name: UTD ASH Website
title: UTD ASH
repository: utdash/ASH-Website

exclude:
  - '.*' # Don't include hidden files
  - Gemfile
  - Gemfile.lock
  - serveLocal.sh
  - serveLocal.bat
  - README.md
  - assets/update_photos.sh
